### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by sharu725** [sharu725/sv-popup#1]
- [x] click outside to close popup
- [x] click escape to close popup
- [x] redesign popup window
